apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80        # ❗ fix this line from 3000 → 80
      nodePort: 30081       # ✅ already valid

